services:
 database:
   image: mysql:latest
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: sampledata
     MYSQL_USER: pentaho
     MYSQL_PASSWORD: password
   ports:
     - 3306:3306
   healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5   
   restart: always
   volumes:
     - mysql_data:/var/lib/mysql

 adminer:
    image: adminer
    restart: always
    ports:
      - 8050:8080

volumes:
 mysql_data: