services:
  jupyter:
    # Base image: Jupyter's official scipy notebook with scientific packages
    image: jupyter/scipy-notebook:latest
    
    # Container name for easy reference in docker commands
    container_name: jupyter-datascience
    
    # Restart policy: automatically restart container if it stops
    restart: unless-stopped
    
    # Port mappings
    ports:
      - "8888:8888"   # Jupyter Lab web interface
    
    # Environment variables
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=datascience
      - TZ=Europe/London
    
    # Volume mappings (Host:Container) - Using Windows-style paths with quotes for spaces
    volumes:
      # Sample datasets directory
      - type: bind
        source: "C:\\Jupyter-Notebook\\datasets"
        target: /home/jovyan/datasets
      # Main notebooks directory
      - type: bind
        source: "C:\\Jupyter-Notebook\\notebooks"
        target: /home/jovyan/notebooks
      # PDI output directory
      - type: bind
        source: "C:\\Jupyter-Notebook\\pdi-output"
        target: /home/jovyan/pdi-output
      # Reports directory
      - type: bind
        source: "C:\\Jupyter-Notebook\\reports"
        target: /home/jovyan/reports  
      # Workshop data directory
      - type: bind
        source: "C:\\Jupyter-Notebook\\workshop-data"
        target: /home/jovyan/work  
    
    # Command to start Jupyter Lab
    command: start-notebook.sh --NotebookApp.token=datascience --ip=0.0.0.0 --port=8888 --no-browser
    
    user: root
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/lab"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
