# Simple Docker Compose configuration for SMB Server
# Deploys Samba SMB server with Bob, Alice, and Shared folders

services:
  samba-server:
    image: dperson/samba:latest
    container_name: smb-workshop-server
    restart: unless-stopped
    
    # Custom ports to avoid conflicts with Windows SMB
    ports:
      - "1139:139"
      - "1445:445"
    
    # Data directories
    volumes:
      - C:/SMB/Bob:/shared/bob
      - C:/SMB/Alice:/shared/alice
      - C:/SMB/Shared:/shared/common
    
    # Samba configuration
    command: >
      -u "bob;password"
      -u "alice;password"
      -s "bob;/shared/bob;yes;no;no;bob;;bob;Bob's Private Files"
      -s "alice;/shared/alice;yes;no;no;alice;;alice;Alice's Private Files"
      -s "shared;/shared/common;yes;no;no;bob,alice;;bob,alice;Shared Team Files"
      -w "WORKGROUP"
